inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

Capybara/FeatureMethods:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "Gemfile"
    - "admin/app/views/admin/*_csv.ruby"
    - "admin/config/routes.rb"
    - "admin/spec/**/*_factory.rb"
    - "admin/spec/**/*_spec.rb"
    - "admin/spec/*_helper.rb"
    - "app/**/*.builder"
    - "app/**/*.jbuilder"
    - "biz/config/routes.rb"
    - "biz/spec/**/*_spec.rb"
    - "config/environments/**/*.rb"
    - "config/routes.rb"
    - "lib/tasks/**/*.rake"
    - "spec/**/*_spec.rb"
    - "spec/*_helper.rb"
    - "spec/factories/*.rb"
    - "bin/setup"

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Layout/DotPosition:
  EnforcedStyle: "leading"
